BEGIN TRANSACTION;
INSERT INTO rol(rol_nombre) VALUES ('chofer');
INSERT INTO rol(rol_nombre) VALUES ('admin');
INSERT INTO rol(rol_nombre) VALUES ('flota');
INSERT INTO rol(rol_nombre) VALUES ('taller');

INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Sin Batea', 'Sin Batea', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 590', 'BQH 590', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 193', 'JOW 193', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 243', 'BUP 243', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 004', 'BNY 004', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 399', 'JUT 399', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('BACO 638', 'HNQ 638', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 038', 'BMP 038', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ RLU-618', 'RLU-618', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 757', 'BUR 757', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 003', 'BNY 003', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 990', 'BNX 990', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'AF549XS', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'MAI 054', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 278', 'BMF 278', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 883', 'BFP 883', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 279', 'BMF 279', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 750', 'BMK 750', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 599', 'RLU 599', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 357', 'BQX 357', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 744', 'BRG 744', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 224', 'BOO 224', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 891', 'BPW-891', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 006', 'BNY 006', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'LDE 471', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('GOMATRO 089', 'RKO 089', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 100', 'RKO 100', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('GOMATRO 043', 'RKO 043', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('ENGERAUTO 993', 'BTD 993', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('BACO 321', 'HLA 321', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROS 606', 'RLU 606', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('BACO 419', 'HKE 419', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 320', 'BGO 320', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'HRI 111', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 642', 'RLU 642', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 711', 'HYS 711', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('BACO 341', 'HTB 341', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('GOMATRO 100', 'RKO 100', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 719', 'HYS 719', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 712', 'HYS 712', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'AF740VE', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 726', 'HYS 726', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 724', 'HYS 724', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'IBG 654', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'IBG 652', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 083', 'RKO 083', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 748', 'BRG 748', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('ENGERAUTO 992', 'BTD 992', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('GOMATRO 026', 'RKO 026', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'IBG 655', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ', 'IBG 653', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('BACO 320', 'HLA 320', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 634', 'RLU 634', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'AF954QF', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 946', 'HGO 946', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'KMJ 543', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 306', 'KZR 306', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 711', 'HYS 711', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROS 606', 'RLU 606', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('BACO 419', 'HKE 419', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('MORALES 320', 'BGO 320', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'HRI 111', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 642', 'RLU 642', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 711', 'HYS 711', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('BACO 341', 'HTB 341', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('GOMATRO 100', 'RKO 100', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 719', 'HYS 719', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 712', 'HYS 712', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('GOMATRO 277', 'RQC 277', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('GOMATRO 544', 'KMJ544', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 726', 'HYS 726', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 724', 'HYS 724', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'IBG 654', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'IBG 652', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 621', 'RLU 621', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'HQB 085', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('BACO 320', 'HLA 320', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 634', 'RLU 634', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'AF954QF', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 946', 'HGO 946', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'KMJ 543', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 920', 'KEN 920', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('BACO 110', 'HRI 110', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 653', 'IBG 653', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'J.C. GIMENEZ', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('GOMATRO 028', 'RKO 028', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'JIC 935', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 366', 'KEV 366', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'RKO 070', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'HYS 712', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'JIC 936', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 934', 'KEN 934', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'LAY 236', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'IUP 631', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JIMENEZ 549', 'AF549XT', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('BACO 477', 'HPA 477', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 346', 'LBI 346', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'RKO 046', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'RKO089', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 385', 'KIY 385', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 298', 'KZR 298', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'KNU 964', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'HGO 946', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 555', 'LXF 555', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'HNQ 637', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 934', 'KEN 934', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'KFV 744', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 083', 'RKO 083', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'AF740VF', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 591', 'RLU 591', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'AF954QE', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('GOMATRO 274', 'RQC 274', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 921', 'KEN 921', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'HRI 111', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 737', 'HYS737', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'HKE 418', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 060', 'RKO 060', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'KTS 214', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('GIMENEZ 791', 'KJZ 791', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 305', 'KZR 305', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'HYS 725', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 635', 'RLU 635', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'KIY 386', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('VULVANO SU758AB', 'AB758SU', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'HLA 321', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('JC GIMENEZ 086', 'HQB 086', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'LYV 591', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('Desconocido', 'AF916RP', 0);
INSERT INTO batea(bat_nombre, bat_dominio, bat_km) VALUES ('DAMBROZ 600', 'RLU 600', 0);


INSERT INTO tipodestino(td_nombre) VALUES ('Nacional');
INSERT INTO tipodestino(td_nombre) VALUES ('Internacional');

INSERT INTO tipocombustible(tc_nombre) VALUES ('Super');
INSERT INTO tipocombustible(tc_nombre) VALUES ('Infinia');
INSERT INTO tipocombustible(tc_nombre) VALUES ('Infinia Diesel');
INSERT INTO tipocombustible(tc_nombre) VALUES ('Shell V-Power Nafta');
INSERT INTO tipocombustible(tc_nombre) VALUES ('Shell V-Power Diesel');
INSERT INTO tipocombustible(tc_nombre) VALUES ('Axion Quantium');
INSERT INTO tipocombustible(tc_nombre) VALUES ('Axion Quantium Diesel');

INSERT INTO tipokilometro(tk_nombre) VALUES ('Kilometros al 100');
INSERT INTO tipokilometro(tk_nombre) VALUES ('Kilometros al 1.2');
INSERT INTO tipokilometro(tk_nombre) VALUES ('Kilometros al 1.4');
INSERT INTO tipokilometro(tk_nombre) VALUES ('Kilometros al 100 1.2');
INSERT INTO tipokilometro(tk_nombre) VALUES ('Kilometros al 100 1.4');

INSERT INTO catnovedad(cn_nombre) VALUES ('Gomeria');
INSERT INTO catnovedad(cn_nombre) VALUES ('Electricidad');
INSERT INTO catnovedad(cn_nombre) VALUES ('Lubricantes/Combustibles');
INSERT INTO catnovedad(cn_nombre) VALUES ('Lavadero');
INSERT INTO catnovedad(cn_nombre) VALUES ('Movilidad');
INSERT INTO catnovedad(cn_nombre) VALUES ('Aduana');
INSERT INTO catnovedad(cn_nombre) VALUES ('Peajes');
INSERT INTO catnovedad(cn_nombre) VALUES ('Peajes Internacionales');
INSERT INTO catnovedad(cn_nombre) VALUES ('Gastos en el exterior');
INSERT INTO catnovedad(cn_nombre) VALUES ('Otros');

COMMIT TRANSACTION;
BEGIN TRANSACTION;

INSERT INTO destino(des_nombre, des_tipo) VALUES ('Destino Nacional',1);
INSERT INTO destino(des_nombre, des_tipo) VALUES ('Tierra del Fuego',2);
INSERT INTO destino(des_nombre, des_tipo) VALUES ('Brazil',2);
INSERT INTO destino(des_nombre, des_tipo) VALUES ('Uruguay',2);
INSERT INTO destino(des_nombre, des_tipo) VALUES ('Paraguay',2);
INSERT INTO destino(des_nombre, des_tipo) VALUES ('Chile',2);
INSERT INTO destino(des_nombre, des_tipo) VALUES ('Bolivia',2);

INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('103 IVECO', 'FJX 327', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('112 FORD', 'EMB 459', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('109 IVECO', 'FHE 229', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('108 IVECO', 'FHE 228', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('134 IVECO', 'GYS 723', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('113 FORD', 'EMG 160', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('111 FORD', 'EOE 424', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('114 FORD', 'EMG 162', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('102 IVECO', 'FHE 230', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('110 IVECO', 'FHE 227', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('302 Iveco', 'AF916RN', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('146 IVECO', 'GYS 719', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('117 FORD', 'END 814', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('118 FORD', 'END 813', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('115 FORD', 'EMG 161', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('119 FORD', 'END 812', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('116 IVECO', 'FTA 712', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('124 FORD', 'EOE 422', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('120 FORD', 'ENW 240', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('121 FORD', 'ENW 241', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('122 FORD', 'ENQ 958', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('125 FORD', 'EOE 423', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('127 IVECO', 'GYS 683', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('138 IVECO', 'GYS 704', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('137 IVECO', 'GYS 725', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('132 IVECO', 'GYS 705', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('144 IVECO', 'GYS 724', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('150 IVECO', 'GYS 707', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('157 IVECO', 'HNQ 629', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('153 IVECO', 'HEG 382', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('155 IVECO', 'HDQ 412', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('152 IVECO', 'HDQ 410', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('154 IVECO', 'HEG 383', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('166 IVECO', 'HPA 478', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('181 IVECO', 'HRC 022', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('164 IVECO', 'HOR 827', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('158 IVECO', 'HNQ 628', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('167 IVECO', 'HPA 479', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('175 IVECO', 'HRC 021', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('186 IVECO', 'HYQ 948', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('168 IVECO', 'HRI 100', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('174 IVECO', 'HRC 019', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('176 IVECO', 'HRI 090', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('172 IVECO', 'HRC 012', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('303 IVECO', 'AF889QT', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('177 IVECO', 'HRI 099', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('170 IVECO', 'HOR 848', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('199 IVECO', 'KFE 814', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('178 IVECO', 'HRI 098', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('180 IVECO', 'HRC 029', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('159 IVECO', 'HNQ 632', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('184 IVECO', 'HRC 013', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('182 IVECO', 'HRC 020', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('145 IVECO', 'GYS 717', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('123 FORD', 'ENQ 959', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('143 IVECO', 'GYS 711', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('149 IVECO', 'GYS 708', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('126 IVECO', 'GYS 682', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('185 IVECO', 'HRC 014', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('183 IVECO', 'HRC 018', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('151 IVECO', 'HEG 381', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('169 IVECO', 'HPH 752', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('148 IVECO', 'GYS 718', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('171 IVECO', 'HPH 751', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('140 IVECO', 'GYS 715', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('306 IVECO', 'AG013FY', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('142 IVECO', 'GYS 709', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('205 IVECO', 'KNU 927', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('208 IVECO', 'KNU 924', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('128 IVECO', 'GYS 684', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('156 IVECO', 'HNQ 630', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('206 IVECO', 'KNU 917', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('204 IVECO', 'KNU 925', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('187 IVECO', 'KHS 279', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('AF916RP IVECO', 'AF916RP', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('AG095TX IVECO', 'AG095TX', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('130 IVECO', 'GYS 716', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('162 IVECO', 'HOR 826', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('189 IVECO', 'KHS 280', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('191 IVECO', 'KFE 813', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('322 IVECO', 'AG210FQ', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('192 IVECO', 'KFE 817', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('151 IVECO', 'HEG 381', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('169 IVECO', 'HPH 752', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('148 IVECO', 'GYS 718', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('171 IVECO', 'HPH751', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('140 IVECO', 'GYS 715', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('306 IVECO', 'AG013FY', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('142 IVECO', 'GYS 709', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('205 IVECO', 'KNU 927', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('208 IVECO', 'KNU 924', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('128 IVECO', 'GYS 684', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('156 IVECO', 'HNQ 630', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('206 IVECO', 'KNU 917', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('204 IVECO', 'KNU 925', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('187 IVECO', 'KHS 279', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('AF916RP IVECO', 'AF916RP', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('AG095TX IVECO', 'AG095TX', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('130 IVECO', 'GYS 716', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('162 IVECO', 'HOR 826', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('189 IVECO', 'KHS 280', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('191 IVECO', 'KFE 813', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('322 IVECO', 'AG210FQ', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('192 IVECO', 'KFE 817', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('129 IVECO', 'GYS 685', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('198 IVECO', 'KHS281', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('210 IVECO', 'KNU 920', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('301 IVECO', 'AF637JC', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('163 IVECO', 'HOR 823', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('211 IVECO', 'KTS 198', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('316 IVECO', 'AF549XM', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('190 IVECO', 'KFE 818', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('203 IVECO', 'KNU 926', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('207 IVECO', 'KNU 919', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('201 IVECO', 'KKD 356', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('318 IVECO', 'AF916RO', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('131 IVECO', 'GYS 710', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('165 IVECO', 'HOR 825', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('188 IVECO', 'KHS 282', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('197 IVECO', 'KFE 833', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('141 IVECO', 'GYS 706', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('304 IVECO', 'AF717ZO', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('133 IVECO', 'GYS 714', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('173 IVECO', 'HRC 028', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('139 IVECO', 'GYS 726', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('147 IVECO', 'GYS 713', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('161 IVECO', 'HNQ 636', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('179 IVECO', 'HRI 091', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('193 IVECO', 'KFE 819', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('194 IVECO', 'KFE 811', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('195 IVECO', 'KFE 812', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('200 IVECO', 'KFE 815', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('209 IVECO', 'KNU 918', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('315 IVECO', 'AF549XL', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('136 IVECO', 'GYS 727', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('202 IVECO', 'KKD 360', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('300 IVECO', 'AF831JI', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('317 IVECO', 'AF889QS', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('323 IVECO', 'AG210FN', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('309 IVECO', 'AG095TX', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('196 IVECO', 'KFE 832', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('321 IVECO', 'AG210FP', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('319 IVECO', 'AF916RP', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('320 IVECO', 'AF831JH', 0, 3);
INSERT INTO flota(flo_nombre, flo_dom_tractor, flo_km_odo, flo_combust_id) VALUES ('135 IVECO', 'GYS 728', 0, 3);

INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jcastillo@elta.com','string','JULIO','CASTILLO',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('fcaceres@elta.com','string','FRANCISCO','CACERES',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('olarrosa@elta.com','string','OSCAR','LARROSA',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('ramaya@elta.com','string','RUBEN ANGEL','AMAYA',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jfernandez@elta.com','string','JOAQUIN','FERNANDEZ',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('ccannata@elta.com','string','CARLOS','CANNATA',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('osaavedra@elta.com','string','OSCAR','SAAVEDRA',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('fosse@elta.com','string','FERNANDO','OSSE',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('dperalta@elta.com','string','DANIEL','PERALTA',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('dmontano@elta.com','string','DANIEL','MONTAÑO',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('overon@elta.com','string','OSCAR','VERON',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('ealberici@elta.com','string','EDUARDO','ALBERICI',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('ogomez@elta.com','string','ORLANDO','GOMEZ',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('ffantin@elta.com','string','FERNANDO','FANTIN',1,NOW(),True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('dsalgado@elta.com', 'string', 'DANIEL', 'SALGADO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('rmenna@elta.com', 'string', 'RAUL', 'MENNA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('hpereyra@elta.com', 'string', 'HUGO', 'PEREYRA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('opilla@elta.com', 'string', 'OMAR', 'PILLA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('nheredia@elta.com', 'string', 'NESTOR', 'HEREDIA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('vnicola@elta.com', 'string', 'VICTOR HUGO', 'NICOLA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('rroldan@elta.com', 'string', 'RAMON', 'ROLDAN', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('csabino@elta.com', 'string', 'CARLOS', 'SABINO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('omartinez@elta.com', 'string', 'OSCAR', 'MARTINEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('osoria@elta.com', 'string', 'OSCAR', 'SORIA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('vbertino@elta.com', 'string', 'VÍCTOR', 'BERTINO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('wortis@elta.com', 'string', 'WALTER', 'ORTIS', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('rrobledo@elta.com', 'string', 'RUBEN', 'ROBLEDO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('dkenny@elta.com', 'string', 'DANIEL', 'KENNY', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('hflores@elta.com', 'string', 'HECTOR', 'FLORES', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('cocanto@elta.com', 'string', 'CARLOS', 'OCANTO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jhuerta@elta.com', 'string', 'JUAN CARLOS', 'HUERTA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jnuñez@elta.com', 'string', 'JORGE', 'NUÑEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jgimenez@elta.com', 'string', 'JOSE', 'GIMENEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('ggilardonni@elta.com', 'string', 'GUSTAVO', 'GILARDONNI', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jjosse@elta.com', 'string', 'JUAN JOSE', 'OSSE', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('ftorres@elta.com', 'string', 'FABIO', 'TORRES', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('msoria@elta.com', 'string', 'MIGUEL', 'SORIA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('camartinez@elta.com', 'string', 'CARLOS ARIEL', 'MARTINEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('rmelano@elta.com', 'string', 'RUBEN', 'MELANO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jsanchez@elta.com', 'string', 'JOSE', 'SANCHEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('aheredia@elta.com', 'string', 'ANDRES', 'HEREDIA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('mgarafo@elta.com', 'string', 'MARCELO', 'GARAFO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('hragno@elta.com', 'string', 'HUGO', 'RAGNO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('aaguirre@elta.com', 'string', 'ALEJANDRO', 'AGUIRRE', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('mgiana@elta.com', 'string', 'MAXIMILIANO', 'GIANA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('harias@elta.com', 'string', 'HUGO', 'ARIAS', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jgonzalez@elta.com', 'string', 'JULIO', 'GONZALEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('molariaga@elta.com', 'string', 'MANUEL', 'OLARIAGA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jrroldan@elta.com', 'string', 'JUAN ROBERTO', 'ROLDAN', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('mmartinez@elta.com', 'string', 'MARIANO', 'MARTINEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jorona@elta.com', 'string', 'JOSE OSVALDO', 'ORONA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('atorres@elta.com', 'string', 'ALEJANDRO', 'TORRES', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('sperez@elta.com', 'string', 'SILVIO', 'PEREZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('cjlemos@elta.com', 'string', 'CLAUDIO JOSE', 'LEMOS', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('fkopelman@elta.com', 'string', 'FEDERICO', 'KOPELMAN', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('ebringas@elta.com', 'string', 'EDUARDO', 'BRINGAS', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('mcontreras@elta.com', 'string', 'MARTIN', 'CONTRERAS', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('candrada@elta.com', 'string', 'CLAUDIO', 'ANDRADA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('dgutierres@elta.com', 'string', 'DANIEL', 'GUTIERRES', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('mfonseca@elta.com', 'string', 'MARIO', 'FONSECA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('glorio@elta.com', 'string', 'GUILLERMO', 'LORIO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jgaravoglia@elta.com', 'string', 'JAVIER', 'GARAVOGLIA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jnieto@elta.com', 'string', 'JAVIER', 'NIETO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('psuarez@elta.com', 'string', 'PABLO', 'SUAREZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('smonteros@elta.com', 'string', 'SERGIO', 'MONTEROS', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('rlarce@elta.com', 'string', 'ROBERTO LUIS', 'ARCE', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('cgalvan@elta.com', 'string', 'CRISTIAN', 'GALVAN', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jbarrantos@elta.com', 'string', 'JUAN', 'BARRIENTOS', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('lsanchez@elta.com', 'string', 'LEONARDO', 'SANCHEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jmnicola@elta.com', 'string', 'JUAN MANUEL', 'NICOLA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('dcampos@elta.com', 'string', 'DAMIAN', 'CAMPOS', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jmoreno@elta.com', 'string', 'JORGE', 'MORENO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('hquintero@elta.com', 'string', 'HUGO', 'QUINTERO', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('mrueda@elta.com', 'string', 'MARCOS', 'RUEDA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('curiarte@elta.com', 'string', 'CRISTIAN', 'URIARTE', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('gstorti@elta.com', 'string', 'GUILLERMO', 'STORTI', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jllopez@elta.com', 'string', 'JOSE LUIS', 'LOPEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('ddemichele@elta.com', 'string', 'DIEGO', 'DE MICHELE', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jpritter@elta.com', 'string', 'JUAN PABLO', 'RITTER', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('sacheverria@elta.com', 'string', 'SERGIO', 'ANDRADA ECHEVERRIA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('mossan@elta.com', 'string', 'MARTIN', 'OSSAN', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('wlopez@elta.com', 'string', 'WALTER', 'LOPEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jpfofre@elta.com', 'string', 'JUAN PABLO', 'FOFRE', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('slachaise@elta.com', 'string', 'SERGIO', 'LACHAISE', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('jcordoba@elta.com', 'string', 'JUAN', 'CORDOBA', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('asmartin@elta.com', 'string', 'ALBERTO', 'SAN MARTIN', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('amatos@elta.com', 'string', 'ANDRES', 'MATOS', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('lchavez@elta.com', 'string', 'LEOPOLDO', 'CHAVEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('dbuscenic@elta.com', 'string', 'DARIO', 'BUSCENIC', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('gdiaz@elta.com', 'string', 'GUSTAVO', 'DIAZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('wgalli@elta.com', 'string', 'WALTER', 'GALLI', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('mceballos@elta.com', 'string', 'MATIAS', 'CEBALLOS', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('dcorotez@elta.com', 'string', 'DARIO', 'CORTEZ', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('nflores@elta.com', 'string', 'NESTOR', 'FLORES', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('cgiusti@elta.com', 'string', 'CARLOS', 'GIUSTI', 1, NOW(), True);
INSERT INTO usuario(usr_email, usr_password, usr_nombre, usr_apellido, usr_rol_id, usr_alta, usr_enable) VALUES ('acordoba@elta.com', 'string', 'ADRIAN', 'CORDOBA', 1, NOW(), True);


INSERT INTO chofer(cho_dni, usr_id) VALUES ('7856850',  1);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('11997406', 2);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('12067996', 3);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('12392945', 4);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('12564885', 5);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('12741468', 6);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('12969646', 7);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('13006452', 8);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('13373655', 9);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('13865599', 10);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('13964123', 11);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('14026000', 12);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('14177320', 13);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('14189884', 14);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('14533031', 15);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('14839437', 16);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('14891739', 17);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('14948987', 18);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('16024131', 19);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('16327531', 20);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('16407894', 21);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('16430777', 22);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('16882415', 23);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('17337785', 24);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('17372993', 25);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('17530954', 26);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('18017953', 27);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('18075568', 28);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('18173939', 29);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('18217539', 30);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('18231950', 31);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('18385602', 32);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('18580132', 33);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('20268731', 34);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('20603937', 35);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('20605451', 36);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('20869863', 37);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('21396413', 38);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('21418568', 39);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('21450993', 40);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('21580345', 41);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('21615912', 42);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('21900827', 43);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('21959738', 44);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('22033444', 45);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('22036349', 46);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('22370702', 47);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('22375268', 48);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('22720758', 49);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('22793453', 50);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('22954670', 51);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('23108397', 52);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('23536603', 53);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('23871390', 54);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('24001658', 55);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('24003172', 56);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('24173615', 57);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('24254030', 58);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('24280767', 59);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('24403338', 60);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('24783404', 61);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('25042638', 62);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('25081942', 63);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('25496946', 64);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('25532096', 65);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('25581078', 66);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('25779560', 67);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('25937090', 68);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('26018967', 69);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('26143199', 70);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('26180002', 71);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('26253064', 72);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('26569237', 73);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('26643206', 74);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('26845588', 75);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('27213097', 76);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('28023453', 77);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('28205714', 78);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('28269394', 79);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('28425857', 80);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('28656278', 81);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('29136980', 82);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('29237997', 83);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('29256761', 84);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('29607971', 85);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('30069607', 86);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('30474888', 87);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('30645325', 88);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('31221802', 89);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('31630352', 90);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('31923297', 91);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('32169858', 92);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('254607016', 93);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('254607022', 94);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('254607025', 95);
INSERT INTO chofer(cho_dni, usr_id) VALUES ('254607029', 96);


COMMIT TRANSACTION;
BEGIN TRANSACTION;

INSERT INTO tipoviatico(tv_nombre, tv_des) VALUES ('Adelanto','ad');
INSERT INTO tipoviatico(tv_nombre, tv_des) VALUES ('Viatico Nacional','via');
INSERT INTO tipoviatico(tv_nombre, tv_des) VALUES ('Viatico Plus','plus');

INSERT INTO Taller(taller_nombre, taller_des) VALUES ('Interno','Taller interno');
INSERT INTO Taller(taller_nombre, taller_des) VALUES ('Externo','Taller externo');

COMMIT TRANSACTION;

